### PR TITLE
Pass Docker Engine Options on Machine Create

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick

### CODE REVIEW

**Comment by cjellick** [comment]
From https://docs.docker.com/machine/reference/create/:

> The supported flags are as follows:
> --engine-insecure-registry: Specify insecure registries to allow with the created engine
> --engine-registry-mirror: Specify registry mirrors to use
> --engine-label: Specify labels for the created engine
> --engine-storage-driver: Specify a storage driver to use with the engine
> ...
> In addition to this subset of daemon flags which are directly supported, Docker Machine also supports an additional flag, --engine-opt, which can be used to specify arbitrary daemon ...

Do we need/want to suppport these options as first class citizens in rancher or is exposing engine-opt enough? If it is enough, we should at least verify that these options can be supported via the generic options.

Also, there is this flag:

> Additionally, Docker Machine supports a flag, `--engine-env`, which can be used to specify arbitrary environment variables to be set within the engine.

Do we want to support engine-env along with engine-opt? Seems like we should

**Comment by cjellick** [comment]
I'd like to see a companion validation-test PR that exercises engine-opt (and the other things I've mentioned if we choose to suppport them).

**Comment by will-chan** [comment]
Yes, I would like to support all those as well if possible.

**Comment by wlan0** [comment]
@cjellick I've added the other fields as well. What kind of validation tests are you thinking of? These fields are set on the host, and these values are not back-populated into the cattle resource. We don't normally test these things. If we wanted to test that these fields are set, then
1. Start backpopulating these fields as well.
2. SSH into the newly created host and inspect manually. 

are the available options.

Let me know what you want to do.

**Comment by cjellick** [comment]
@wlan0 another option: hosts have a dockersocket action that gives you direct access to the docker daemon's socket, which would allow you to run docker info (assuming the information is in there?)

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
Closing in favor of #70 because it has updated godep

**Pull request closed without merging**
